#!/usr/bin/env python

import RPi.GPIO as GPIO
import time
import serial
import asyncio
import numpy as np
from sendStringScript import sendString

state = "idle"
x=int(0)
leftMotor=int(0)
rightMotor=int(0)

intersection_counter = 0
counter = 0
crossprev = 0
counter2 = 0
inTurn = 0

sensor_L = 4
sensor_M = 17
sensor_R = 18
TRIG_1 = 27
ECHO_1 = 22
GPIO.setmode(GPIO.BCM)
GPIO.setup(sensor_L,GPIO.IN)
GPIO.setup(sensor_M,GPIO.IN)
GPIO.setup(sensor_R,GPIO.IN)
GPIO.setup(TRIG_1, GPIO.OUT)
GPIO.setup(ECHO_1, GPIO.IN)

def IRcheck(sensor):
	time.sleep(0.5)
	irValue = GPIO.input(sensor)
	if irValue:
		IR = 0
		print(f"NOT DETECTED Sensor {sensor}")
				
	else:
		IR = 1
		print(f"DETECTED Sensor {sensor}")

	return IR

def get_distance(TRIG,ECHO):
    """Measure distance using HC-SR04 (in cm)."""
    # Ensure trigger is LOW
    GPIO.output(TRIG, False)
    time.sleep(0.05)

    # Send 10µs pulse
    GPIO.output(TRIG, True)
    time.sleep(0.00001)
    GPIO.output(TRIG, False)

    # Wait for echo start
    start = time.time()
    timeout = start + 0.02  # 20ms safety timeout
    while GPIO.input(ECHO) == 0 and time.time() < timeout:
        start = time.time()

    # Wait for echo end
    stop = time.time()
    timeout = stop + 0.02
    while GPIO.input(ECHO) == 1 and time.time() < timeout:
        stop = time.time()

    # Compute distance
    elapsed = stop - start
    distance_cm = (elapsed * 34300) / 2
    return round(distance_cm, 2)
     
def count():
    global counter, crossprev, cross
    if cross==1 and crossprev!=1:
        counter +=1
        crossprev=cross
        #print(counter) 
    else :
        crossprev=cross

        return counter

    # --- Main loop ---
if __name__ == '__main__':
    ser=serial.Serial('/dev/ttyACM0',9600)
    ser.reset_input_buffer() #clears anything the arduino has been sending while the Rpi isnt prepared to recieve.

    while True:
        sendString('/dev/ttyACM0',9600,'<'+str(leftMotor)+','+str(rightMotor)+'>',0.0001)
        
        if ser.in_waiting > 0:  #we wait until the arduino has sent something to us before we try to read anything from the serial port.
                 
                line = ser.readline().decode('utf-8')
                line=line.split(',')
                #print(line)
                #this splits the incoming string up by commas
                try:                  
                    x=int(line[0])
                    pos=int(line[1])
                    cross=int(line[2])
                    #L=float(line[3])
                    #R=float(line[4])
                    #print([x,pos,cross])
                    #print(L,R)
                    intersection_counter = count()
                    if pos < 500 and state != "initialForward" and state != "idle":
                        state="Indeterminant" 
                except:
                    print("packet dropped") #this is designed to catch when python shoves bits on top of each other.                 
          
        match state:
            case "idle":
                print("idle")
                if x==1: 
                    state = "initialForward"
                
                #state = "Following"
            case "initialForward":
                print("initialForward")
                leftMotor = 5
                rightMotor = 5
                if cross ==1:
                    leftMotor = 0
                    rightMotor = 0
                    dist_1 = get_distance(TRIG_1,ECHO_1)
                    if dist_1 > 1000:
                        inTurn = 1
                        state = "turnRight1"
                    else: 
                        inTurn = 0
                        state = "turnLeft1"
            case "turnRight1":
                print("Initial Turn Right")
                leftMotor=5  
                rightMotor=-5
                time.sleep(.9)
                counter = 0    
                state = "Following"
            case "turnLeft1":
                print("Initial Turn Left")
                leftMotor=-5  
                rightMotor=5
                time.sleep(.9)
                counter = 0    
                state = "Following"
            case "Following":
                print("Line Following")
                error = (pos-3500)/3500
                rightMotor = max(0,min(20,2 - 3*error))
                leftMotor = max(0,min(20,2 + 3*error))
                print("PID: ",leftMotor,rightMotor)
                if counter == 1 and counter2 == 0 and inTurn == 0:
                    state = "turnLeft"
                elif counter == 1 and counter2 == 0 and inTurn == 1:
                    state = "turnRight"
                elif counter == 2:
                    state = "Destination"
            case "turnLeft":
                print("turnLeft")
                leftMotor=-5  
                rightMotor=5
                time.sleep(.9)
                counter2 = 1   
                state = "Following"
            case "turnRight":
                print("turnRight")
                leftMotor=5  
                rightMotor=-5
                time.sleep(.9)
                counter2 = 1   
                state = "Following"
            case "Destination":
                print("Destination")
                leftMotor, rightMotor = (0, 0);
                L =  IRcheck(sensor_L)
                M =  IRcheck(sensor_M)
                R =  IRcheck(sensor_R)
                #if L ==1 :
                 #   state = "shootLeft"
                #elif M ==1:
                 #    state = "shootMid"
                #elif R == 1:
                 #    state = "shootRight"
            case "shootLeft":
                print("shootLeft")
                leftMotor=-5  
                rightMotor=5
                time.sleep(.5)
                leftMotor=0  
                rightMotor=0
                time.sleep(3)
                leftMotor=5  
                rightMotor=-5
                time.sleep(.5)
                state = "Destination"
            case "shootRight":
                print("shootRight")
                leftMotor=5  
                rightMotor=-5
                time.sleep(.5)
                leftMotor=0  
                rightMotor=0
                time.sleep(3) 
                leftMotor=-5  
                rightMotor=5
                time.sleep(.5)
                state = "Destination" 
            case "shootMid":
                print("shootMid")
                leftMotor=0  
                rightMotor=0
                time.sleep(3) 
                state = "Destination"   
            case "Indeterminant":
                print("Indeterminant")
                leftMotor, rightMotor = (0, 0);
                if pos > 500:
                    state = "Following"
